spring:
  application:
    name: health-check-demo

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/healthcheck
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
